# Generated by Django 5.2.11 on 2026-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_lead_assigned_to_lead_followup_time_lead_temperature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="property_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
