# Generated by Django 5.2.11 on 2026-02-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_lead_property_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Apartment", "Apartment"),
                    ("Villa", "Villa"),
                    ("Plot", "Plot"),
                    ("Commercial", "Commercial"),
                    ("Office", "Office"),
                    ("Shop", "Shop"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
