# Generated by Django 5.2.11 on 2026-03-02 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_alter_lead_property_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="followup_date",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="followup_time",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="status",
        ),
        migrations.AddField(
            model_name="lead",
            name="agreement_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="bhk",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1 BHK", "1 BHK"),
                    ("2 BHK", "2 BHK"),
                    ("3 BHK", "3 BHK"),
                    ("4 BHK", "4 BHK"),
                    ("5 BHK", "5 BHK"),
                    ("NA", "NA"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="brochure_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="location_preference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="lost_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Budget Issue", "Budget Issue"),
                    ("Location Issue", "Location Issue"),
                    ("Went to Competitor", "Went to Competitor"),
                    ("Not Interested", "Not Interested"),
                    ("No Response", "No Response"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="pipeline",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Contacted", "Contacted"),
                    ("Site Visit Scheduled", "Site Visit Scheduled"),
                    ("Site Visit Done", "Site Visit Done"),
                    ("Negotiation", "Negotiation"),
                    ("Closed Won", "Closed Won"),
                    ("Closed Lost", "Closed Lost"),
                ],
                default="New",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="price_list_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Self Use", "Self Use"),
                    ("Investment", "Investment"),
                    ("Rental", "Rental"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="site_visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="site_visit_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="site_visit_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("Facebook", "Facebook"),
                    ("Google", "Google"),
                    ("99acres", "99acres"),
                    ("MagicBricks", "MagicBricks"),
                    ("Reference", "Reference"),
                    ("Walk-in", "Walk-in"),
                    ("Hoarding", "Hoarding"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Immediate", "Immediate"),
                    ("1-3 Months", "1-3 Months"),
                    ("3-6 Months", "3-6 Months"),
                    ("6-12 Months", "6-12 Months"),
                    ("Just Exploring", "Just Exploring"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Flat", "Flat"),
                    ("Villa", "Villa"),
                    ("Plot", "Plot"),
                    ("Commercial", "Commercial"),
                    ("Office", "Office"),
                    ("Shop", "Shop"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="temperature",
            field=models.CharField(
                choices=[
                    ("Hot", "Hot"),
                    ("Warm", "Warm"),
                    ("Cold", "Cold"),
                    ("Dead", "Dead"),
                ],
                default="Cold",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Followup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="leads.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
