# Generated by Django 5.2.11 on 2026-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0005_remove_lead_followup_date_remove_lead_followup_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
